name: Docker Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: |
        docker-compose --file docker-compose.yml \
          up --build --detach --timeout 30
    - name: Stop containers
      if: always()
      run: docker-compose --file docker-compose.yml down
    
